Fixing Music Search
Ombi-app/Ombi pull request #4288
Opened 2021-08-09 21:22 UTC by Fyb3roptik

Music search now searches via Lidarr. It can now handle Artists and Albums. Please don't hate me for this giant PR

2021-08-10 19:38 UTC, tidusjar requested changes
Looks good so far. I need to pull it down and do some manual testing !

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Api.Lidarr/LidarrApi.cs
> +            Console.Write(request);
Please can we remove this

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Api.Lidarr/LidarrApi.cs
> +            Console.Write(artist);
Can we also remove this

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core.Tests/Engine/V2/MusicSearchEngineV2Tests.cs
> +        // private Mock<ILidarrApi> _musicApi;
Remove

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core/Engine/V2/MultiSearchEngine.cs
> +            if (filter.Movies)
This is not going to work, if we just have TV in the filter it’s not going to show anything

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core/Engine/V2/MusicSearchEngineV2.cs
> -                ReleaseDate = g.ReleaseGroup.FirstReleaseDate,
The task could be null, so an exception could be thrown here when lidarr is not enabled

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core/Engine/V2/MusicSearchEngineV2.cs
> -            {
Are we not losing data now?

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core/Engine/V2/MusicSearchEngineV2.cs
> +        public async Task<AlbumArt> GetReleaseGroupArt(string musicBrainzId, CancellationToken token)
Is anything calling this API?

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core/Engine/V2/MusicSearchEngineV2.cs
> +            // foreach (var relation in artist.Relations)
Please remove the method if not used

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core/Engine/V2/MusicSearchEngineV2.cs
>          private List<BandMember> GetBandMembers(Artist artist)
Please remove the method if not used

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core/Models/Search/V2/Music/AlbumInformation.cs
> +        public bool IsEnded => EndYear != null;
Use string.IsNullOrEmpty instead of the != operator

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Core/Senders/MusicSender.cs
> +            Console.Write(model);
Please remove

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Store/Entities/RequestType.cs
> +        Artist = 2,
This might break existing requests  They will be stored in the database as type 2. But albums are now type 3

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Store/Migrations/OmbiMySql/20210802192907_RenameAlbumRequests.cs
> +        {
This migration is wrong  There should be more than just a table rename here

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi.Store/Migrations/OmbiMySql/20210802192907_RenameAlbumRequests.cs
> +        {
OH nevermind. I see there are two migrations

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.html
> +            {{ result.title }}
I don't think we spoke about this, the text should say what type of media it is.

2021-08-10 19:38 UTC, tidusjar commented on src/Ombi/Controllers/V1/MusicRequestController.cs
> +            Console.Write(artist);
Please remove

2021-08-10 22:42 UTC, Fyb3roptik reviewed
Should have resolved all issues

2021-08-16 11:42 UTC, tidusjar commented
Only just seen that you resolved the issue. I'll take a look soon!

2021-09-08 19:22 UTC, tidusjar commented
Looks like the search results and all of the cards show the Buttons, they should only show on hover, not sure how you have changed so much of the discover card stuff!

When requesting an album from the search screen it doesn't call out to the API (so currently you cannot request individual albums from the search), artists work fine.

The request buttons should be above the Artist information on the detail page.

I'm going to merge this into a feature branch `feature/music-rework` any future PR's we can target that until this is ready to be merged into develop

2021-09-08 19:23 UTC, merged

2021-09-09 15:19 UTC, Fyb3roptik commented
Perfect! I will get to work on these changes!