Send new request email notifications to power users
Ombi-app/Ombi pull request #4462
Opened 2022-01-10 12:12 UTC by sephrat

This provides the possibility to send "New Request" notifications to power users instead of the Ombi administrator.
On top of that, if Ombi has multiple admins, an email will be sent to all admins instead of the "Admin Email" set up in the notifications settings.

I tagged this as a draft because I'm not sure about the setting I added:
1. I'm not sure it should even be a setting since it makes more sense that way IMO. Why send the notification to a fraction of the population that is allowed to approve the request? 
2. This could be extended to mobile notifications (at least), but then that would make it a more global setting than an email one - probably a "New Request" notification template?

2022-01-11 09:33 UTC, tidusjar commented
Yeah,

I mentioned a setting to prevent any issues and make it backwards compatible. But I agree it does make sense to be a default, if someone doesn't like it then we can alter that in the future.

Also regarding the other notification types, it should really apply to all (inc. mobile).

2022-01-11 15:27 UTC, sephrat commented
I've added the logic to mobile notifications, although I could not test this myself.
I could not find the logic for recipients determination for other notifications types such as Pushbullet, Discord, ... . How do you take into account users' tokens and how do you know in which case to send it to who?

2022-01-11 15:38 UTC, tidusjar commented
For the other agents, the notifications are published to the channels, so it's only really Email and Mobile that will go to individual users currently

2022-01-14 09:39 UTC, tidusjar commented on src/Ombi.Notifications/BaseNotification.cs
> +        protected async Task<IEnumerable<OmbiUser>> GetPowerUsers()
This is not really getting power users, It's getting all users that have raised privilidges

2022-01-14 09:51 UTC, tidusjar requested changes

2022-01-14 09:51 UTC, tidusjar commented on src/Ombi.Notifications/Agents/LegacyMobileNotification.cs
> +        private async Task<List<string>> GetPowerUsersPlayerIds()
This is not used?

2022-01-14 09:51 UTC, tidusjar commented on src/Ombi.Notifications/Agents/LegacyMobileNotification.cs
> +        private async Task<List<string>> GetAdmins()
I suggest we just rename this to `GetNotificationRecipients`.

    private async Task<List<string>> GetNotificationRecipients() => await UsersToPlayerIds(await GetAdminAndPowerRecipients());

2022-01-14 13:06 UTC, tidusjar commented
We probably want to apply this to the following notification types:

* NewIssue
* IssueComment
* AddedToRequestQueue


I think we should just remove `GetAdmins()` from the MobileNotification.cs and always use `GetPrivilegedUsersPlayerIds`

2022-01-14 13:57 UTC, sephrat commented
Mmmh, I thought about it but tend to disagree on this. My interpretation of the difference between an admin and a power user is as follows:

- Admins are tech-savvy users, they're the ones who will know about the *arr apps, so if there's an issue with a media or an integration with the *arr, they're the ones who can sort this. 
- Power users are users who can also review requests, they're not necessarily tech-savvy. They don't have access to the settings page so they're not supposed to know how to sort out issues or integration errors.

Does that make sense?

2022-01-14 14:23 UTC, tidusjar commented
Fair, you got me there. I agree with your points... I guess that they couldn't resolve issues either in that case...

2022-01-14 14:24 UTC, merged